## Regression Model

In [1]:
from sklearn.datasets import load_boston

In [2]:
boston =load_boston()

In [3]:
type(boston)

sklearn.utils.Bunch

In [4]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [5]:
X=boston.data

In [7]:
y=boston.target

## train and test on the entire datasets

## Simple linear regression

In [9]:
X_rooms=X[:,5]

In [10]:
X_rooms

array([6.575, 6.421, 7.185, 6.998, 7.147, 6.43 , 6.012, 6.172, 5.631,
       6.004, 6.377, 6.009, 5.889, 5.949, 6.096, 5.834, 5.935, 5.99 ,
       5.456, 5.727, 5.57 , 5.965, 6.142, 5.813, 5.924, 5.599, 5.813,
       6.047, 6.495, 6.674, 5.713, 6.072, 5.95 , 5.701, 6.096, 5.933,
       5.841, 5.85 , 5.966, 6.595, 7.024, 6.77 , 6.169, 6.211, 6.069,
       5.682, 5.786, 6.03 , 5.399, 5.602, 5.963, 6.115, 6.511, 5.998,
       5.888, 7.249, 6.383, 6.816, 6.145, 5.927, 5.741, 5.966, 6.456,
       6.762, 7.104, 6.29 , 5.787, 5.878, 5.594, 5.885, 6.417, 5.961,
       6.065, 6.245, 6.273, 6.286, 6.279, 6.14 , 6.232, 5.874, 6.727,
       6.619, 6.302, 6.167, 6.389, 6.63 , 6.015, 6.121, 7.007, 7.079,
       6.417, 6.405, 6.442, 6.211, 6.249, 6.625, 6.163, 8.069, 7.82 ,
       7.416, 6.727, 6.781, 6.405, 6.137, 6.167, 5.851, 5.836, 6.127,
       6.474, 6.229, 6.195, 6.715, 5.913, 6.092, 6.254, 5.928, 6.176,
       6.021, 5.872, 5.731, 5.87 , 6.004, 5.961, 5.856, 5.879, 5.986,
       5.613, 5.693,

In [11]:
X_rooms=X_rooms.reshape(-1,1)

In [12]:
X_rooms

array([[6.575],
       [6.421],
       [7.185],
       [6.998],
       [7.147],
       [6.43 ],
       [6.012],
       [6.172],
       [5.631],
       [6.004],
       [6.377],
       [6.009],
       [5.889],
       [5.949],
       [6.096],
       [5.834],
       [5.935],
       [5.99 ],
       [5.456],
       [5.727],
       [5.57 ],
       [5.965],
       [6.142],
       [5.813],
       [5.924],
       [5.599],
       [5.813],
       [6.047],
       [6.495],
       [6.674],
       [5.713],
       [6.072],
       [5.95 ],
       [5.701],
       [6.096],
       [5.933],
       [5.841],
       [5.85 ],
       [5.966],
       [6.595],
       [7.024],
       [6.77 ],
       [6.169],
       [6.211],
       [6.069],
       [5.682],
       [5.786],
       [6.03 ],
       [5.399],
       [5.602],
       [5.963],
       [6.115],
       [6.511],
       [5.998],
       [5.888],
       [7.249],
       [6.383],
       [6.816],
       [6.145],
       [5.927],
       [5.741],
       [5.966],
       [

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
model =LinearRegression()

In [15]:
model.fit(X_rooms,y)

LinearRegression()

In [16]:
model.coef_

array([9.10210898])

In [17]:
model.intercept_

-34.67062077643857

In [18]:
model.score(X_rooms,y)

0.48352545599133423

## Multiple linear regression

In [19]:
model1=LinearRegression()
model1.fit(X,y)

LinearRegression()

In [20]:
model1.score(X,y)

0.7406426641094095

## Train test split

In [21]:
from sklearn.model_selection import train_test_split


## Linear regression

In [26]:
X_train_r,X_test_r,y_train_r,y_test_r=train_test_split(X_rooms,y,test_size=0.3)

In [27]:
X_train_r.shape

(354, 1)

In [28]:
354/506

0.6996047430830039

In [29]:
X_test_r.shape

(152, 1)

In [30]:
152/506

0.30039525691699603

In [32]:
model2=LinearRegression()
model2.fit(X_train_r,y_train_r)

LinearRegression()

In [33]:
model2.score(X_test_r,y_test_r)

0.48305143687207075

## Mult linear regression

In [34]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [35]:
model3=LinearRegression()

In [36]:
model3.fit(X_train,y_train)

LinearRegression()

In [38]:
model3.score(X_test,y_test)

0.7017720305509958

## using two attributes

In [41]:
X_two=X[:,:2]

In [43]:
X_two.shape

(506, 2)

In [52]:
X_train_t,X_test_t,y_train_t,y_test_t=train_test_split(X_two,y)

In [53]:
model5=LinearRegression()
model5.fit(X_train_t,y_train_t)

LinearRegression()

In [54]:
model5.score(X_test_t,y_test_t) ## test score

0.12131847769360482

In [55]:
model5.score(X_train_t,y_train_t) ## train score

0.26907922605012746

In [50]:
model3.coef_

array([-8.01955629e-02,  5.02346735e-02,  1.14715415e-02,  2.57363031e+00,
       -1.53769959e+01,  4.08045116e+00, -1.24497060e-02, -1.53507345e+00,
        2.87433433e-01, -1.26733454e-02, -9.51397616e-01,  1.11697071e-02,
       -4.43026638e-01])

In [51]:
model5.coef_

array([-0.33946157,  0.12093801])

## Medical Cost dataset

In [56]:
import pandas as pdDesktop/main/DS-Training-2022/datasets/insurance.csv

In [58]:
df=pd.read_csv("../../../datasets/insurance.csv")

In [59]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [61]:
df.shape

(1338, 7)

## Linear regression of charge on BMI

In [62]:
X=df.bmi

In [63]:
X

0       27.900
1       33.770
2       33.000
3       22.705
4       28.880
         ...  
1333    30.970
1334    31.920
1335    36.850
1336    25.800
1337    29.070
Name: bmi, Length: 1338, dtype: float64

In [64]:
y=df.charges

In [65]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...     
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [66]:
model_bmi1=LinearRegression()

In [67]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [69]:
X_train,X_test=X_train.reshape(-1,1),X_test.reshape(-1,1)
model_bmi1.fit(X_train,y_train)

AttributeError: 'Series' object has no attribute 'reshape'

In [72]:
X_train,X_test=X_train.values.reshape(-1,1),X_test.values.reshape(-1,1)
model_bmi1.fit(X_train,y_train)

LinearRegression()

In [73]:
model_bmi1.score(X_test,y_test)

-0.022603579734747914

## Scale the data 

In [74]:
X

0       27.900
1       33.770
2       33.000
3       22.705
4       28.880
         ...  
1333    30.970
1334    31.920
1335    36.850
1336    25.800
1337    29.070
Name: bmi, Length: 1338, dtype: float64

In [75]:
X=X/X.max()

In [77]:
X

0       0.525127
1       0.635611
2       0.621118
3       0.427348
4       0.543572
          ...   
1333    0.582910
1334    0.600791
1335    0.693582
1336    0.485601
1337    0.547149
Name: bmi, Length: 1338, dtype: float64

In [78]:
X_train,X_test,y_train,y_test=train_test_split(X,y)
X_train,X_test=X_train.values.reshape(-1,1),X_test.values.reshape(-1,1)
model_bmi1.fit(X_train,y_train)
model_bmi1.score(X_test,y_test)

-0.003077165731920628

In [79]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## Linear model of charge on BMI and Age

In [82]:
X=df.iloc[:,[0,2]]

In [83]:
X

age     bmi
0      19  27.900
1      18  33.770
2      28  33.000
3      33  22.705
4      32  28.880
...   ...     ...
1333   50  30.970
1334   18  31.920
1335   18  36.850
1336   21  25.800
1337   61  29.070

[1338 rows x 2 columns]

In [92]:
model_comb1=LinearRegression()
X_train,X_test,y_train,y_test=train_test_split(X,y)
# X_train,X_test=X_train.values.reshape(-1,1),X_test.values.reshape(-1,1)
model_comb1.fit(X_train,y_train)
model_comb1.score(X_test,y_test)

0.07478443978301808

In [93]:
def getScore(X,y):
    model=LinearRegression()
    X_train,X_test,y_train,y_test=train_test_split(X,y)
    if(X.ndim==1):
        X_train,X_test=X_train.values.reshape(-1,1),X_test.values.reshape(-1,1)
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [85]:
X

age     bmi
0      19  27.900
1      18  33.770
2      28  33.000
3      33  22.705
4      32  28.880
...   ...     ...
1333   50  30.970
1334   18  31.920
1335   18  36.850
1336   21  25.800
1337   61  29.070

[1338 rows x 2 columns]

In [88]:
df["age_sc"]=df.age/X.age.mean()
df["bmi_sc"]=df.bmi/X.bmi.mean()

In [89]:
df

age     sex     bmi  children smoker     region      charges    age_sc  \
0      19  female  27.900         0    yes  southwest  16884.92400  0.484607   
1      18    male  33.770         1     no  southeast   1725.55230  0.459101   
2      28    male  33.000         3     no  southeast   4449.46200  0.714158   
3      33    male  22.705         0     no  northwest  21984.47061  0.841686   
4      32    male  28.880         0     no  northwest   3866.85520  0.816180   
...   ...     ...     ...       ...    ...        ...          ...       ...   
1333   50    male  30.970         3     no  northwest  10600.54830  1.275282   
1334   18  female  31.920         0     no  northeast   2205.98080  0.459101   
1335   18  female  36.850         0     no  southeast   1629.83350  0.459101   
1336   21  female  25.800         0     no  southwest   2007.94500  0.535618   
1337   61  female  29.070         0    yes  northwest  29141.36030  1.555844   

        bmi_sc  
0     0.909880  
1     1.101313  
2     1.076202  
3     0.740459  
4     0.941840  
...        ...  
1333  1.009999  
1334  1.040981  
1335  1.201759  
1336  0.841394  
1337  0.948036  

[1338 rows x 9 columns]

In [90]:
X=df.iloc[:,[-1,-2]]

In [91]:
X

bmi_sc    age_sc
0     0.909880  0.484607
1     1.101313  0.459101
2     1.076202  0.714158
3     0.740459  0.841686
4     0.941840  0.816180
...        ...       ...
1333  1.009999  1.275282
1334  1.040981  0.459101
1335  1.201759  0.459101
1336  0.841394  0.535618
1337  0.948036  1.555844

[1338 rows x 2 columns]

In [94]:
getScore(X,y)

0.07327273238330678