In [1]:
import numpy as np

In [2]:
x=np.array([2,7,9,14,15,12,7])

In [3]:
x[0:7:3]

array([ 2, 14,  7])

In [4]:
y=np.array([[3,4],[9,2],[-3,5]])

In [5]:
y[0:2:]

array([[3, 4],
       [9, 2]])

In [6]:
y[:2,:]

array([[3, 4],
       [9, 2]])

In [7]:
z=np.array([[3,2,1],[4,1,7],[1,1,-3],[7,7,-2]])

In [8]:
z[1:3,0:2]

array([[4, 1],
       [1, 1]])

In [12]:
z[2:4,1:3]

array([[ 1, -3],
       [ 7, -2]])

In [13]:
z[:,0:2]

array([[3, 2],
       [4, 1],
       [1, 1],
       [7, 7]])

## Fancy Indexing


In [19]:
a=np.array([3,2,4,9,5,15])

In [20]:
a[[0,2,4,5]]

array([ 3,  4,  5, 15])

In [21]:
z[[0,0,2,2],[0,1,1,2]]

array([ 3,  2,  1, -3])

In [23]:
m=np.mean(x)

In [24]:
m

9.428571428571429

In [25]:
x>m

array([False, False, False,  True,  True,  True, False])

In [26]:
result=x>m

In [27]:
x[result]

array([14, 15, 12])

## Reshaping

In [36]:
x1=x[1:]

In [37]:
x1

array([ 7,  9, 14, 15, 12,  7])

In [38]:
x1.shape

(6,)

In [39]:
x1.size

6

In [40]:
x1.shape=(2,3)

In [41]:
x1

array([[ 7,  9, 14],
       [15, 12,  7]])

In [44]:
x2=x[1:]

In [45]:
x2

array([ 7,  9, 14, 15, 12,  7])

In [46]:
x2.reshape(3,2)

array([[ 7,  9],
       [14, 15],
       [12,  7]])

In [47]:
 x2

array([ 7,  9, 14, 15, 12,  7])

In [48]:
z

array([[ 3,  2,  1],
       [ 4,  1,  7],
       [ 1,  1, -3],
       [ 7,  7, -2]])

In [49]:
z.reshape(1,12)  #12 column any no of row

array([[ 3,  2,  1,  4,  1,  7,  1,  1, -3,  7,  7, -2]])

In [51]:
z.reshape(-1,6)  #6 columns any no of row

array([[ 3,  2,  1,  4,  1,  7],
       [ 1,  1, -3,  7,  7, -2]])

In [ ]:
# shape change old entry to new one while reshape change old entry and display new method but can still return old